runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -k tornado app:application

runtime_config:
  python_version: 3

health_check:
  enable_health_check: False

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1